Check for .vagrant.d

diff --git a/kubeup b/kubeup
--- a/kubeup
+++ b/kubeup
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+# Check ~/.vagrant.d exists
+
+if [ ! -d ${HOME}/.vagrant.d ] ; then
+	if ! vagrant version > /dev/null 2>&1 ; then
+		echo "Directory ~/.vagrant.d is missing. Please create it by installing vagrant and typing: vagrant version"
+	fi
+fi
+
 docker run -it --rm \
 	-e LIBVIRT_DEFAULT_URI \
 	-v /var/run/libvirt/:/var/run/libvirt/ \
